### ISSUE TITLE
Error installing on Magento 2.2.2

### ISSUE THREAD

**Issue by rishabhchd19** [pmclain/module-twilio#14]
I found it is not compatible with Magento 2.2.2. 
![2017-12-27_1-09-22](https://user-images.githubusercontent.com/30948461/34363603-93a7499a-eaa3-11e7-91c0-8ac51213bd7a.jpg)

Any update?

**Comment by pmclain** [comment]
Magento 2.2 dropped support for PHP 5.

**Comment by rishabhchd19** [comment]
Any future work on this module for Magento 2.2?

**Comment by pmclain** [comment]
The module works with Magento 2.2, but you will not be able to install this module via composer until your server meets the requirements for Magento 2.2. The composer error in the screenshot is telling you to upgrade your version of php to meet the minimum requirements for the `magento/framework` package.
