### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by dawhoo** [pmclain/module-twilio#16]
Having a really hard time uninstalling, even after cleaning the DB. Are there persistent files stored outside if the pmclain folder?

**Comment by pmclain** [comment]
Just the Twilio SDK dependency declared in `composer.json`

**Comment by kurapatijayaram** [comment]
I have installed your module manuaaly by copying the code to app folder. Even after I disable the module I can see SMS Notifcation checkbox at checkout page. I also removed this module related records that exists in setup_module and core_config_data . Can you pls help me.

**Comment by pmclain** [comment]
Redeploy static content will remove the templates lingering in pub/static.
