### ISSUE TITLE
Class Twilio\Rest\ClientFactory does not exist issue

### ISSUE THREAD

**Issue by PrathapMadhavan** [pmclain/module-twilio#17]
We face an issue when compile time :  " Class Twilio\Rest\ClientFactory does not exist"

Can u please help.

**Comment by pmclain** [comment]
Can you share the Magento version you are using and how you installed the module?

**Comment by PrathapMadhavan** [comment]
We have use  Magento ver. 2.2.3  and we download from git  then we extract app/code folder the we run CLI comments.

**Comment by pmclain** [comment]
There is a dependency on the twilio sdk.  You are responsible for resolving the dependencies defined in ’composer.json’ when you don’t install via composer.
